# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"


  # Maintain dependencies for maven
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.keycloak:*"
      - dependency-name: "io.quarkus:*"
      - dependency-name: "org.apache.*"
      - dependency-name: "commons-*"
      - dependency-name: "com.github.ben-manes.caffeine:*"
      - dependency-name: "org.slf4j:*"
      - dependency-name: "org.testcontainers:*"
    commit-message:
      include: "scope"
      prefix: "chore"
